/*
Vault Hub Server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuditLogsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuditLogsResponse{}

// AuditLogsResponse struct for AuditLogsResponse
type AuditLogsResponse struct {
	AuditLogs []AuditLog `json:"auditLogs"`
	// Total number of logs matching the filter criteria
	TotalCount int32 `json:"totalCount"`
	// Number of logs per page
	PageSize int32 `json:"pageSize"`
	// Current page index (starting from 0)
	PageIndex int32 `json:"pageIndex"`
}

type _AuditLogsResponse AuditLogsResponse

// NewAuditLogsResponse instantiates a new AuditLogsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuditLogsResponse(auditLogs []AuditLog, totalCount int32, pageSize int32, pageIndex int32) *AuditLogsResponse {
	this := AuditLogsResponse{}
	this.AuditLogs = auditLogs
	this.TotalCount = totalCount
	this.PageSize = pageSize
	this.PageIndex = pageIndex
	return &this
}

// NewAuditLogsResponseWithDefaults instantiates a new AuditLogsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuditLogsResponseWithDefaults() *AuditLogsResponse {
	this := AuditLogsResponse{}
	return &this
}

// GetAuditLogs returns the AuditLogs field value
func (o *AuditLogsResponse) GetAuditLogs() []AuditLog {
	if o == nil {
		var ret []AuditLog
		return ret
	}

	return o.AuditLogs
}

// GetAuditLogsOk returns a tuple with the AuditLogs field value
// and a boolean to check if the value has been set.
func (o *AuditLogsResponse) GetAuditLogsOk() ([]AuditLog, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuditLogs, true
}

// SetAuditLogs sets field value
func (o *AuditLogsResponse) SetAuditLogs(v []AuditLog) {
	o.AuditLogs = v
}

// GetTotalCount returns the TotalCount field value
func (o *AuditLogsResponse) GetTotalCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *AuditLogsResponse) GetTotalCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *AuditLogsResponse) SetTotalCount(v int32) {
	o.TotalCount = v
}

// GetPageSize returns the PageSize field value
func (o *AuditLogsResponse) GetPageSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *AuditLogsResponse) GetPageSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *AuditLogsResponse) SetPageSize(v int32) {
	o.PageSize = v
}

// GetPageIndex returns the PageIndex field value
func (o *AuditLogsResponse) GetPageIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageIndex
}

// GetPageIndexOk returns a tuple with the PageIndex field value
// and a boolean to check if the value has been set.
func (o *AuditLogsResponse) GetPageIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageIndex, true
}

// SetPageIndex sets field value
func (o *AuditLogsResponse) SetPageIndex(v int32) {
	o.PageIndex = v
}

func (o AuditLogsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuditLogsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["auditLogs"] = o.AuditLogs
	toSerialize["totalCount"] = o.TotalCount
	toSerialize["pageSize"] = o.PageSize
	toSerialize["pageIndex"] = o.PageIndex
	return toSerialize, nil
}

func (o *AuditLogsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"auditLogs",
		"totalCount",
		"pageSize",
		"pageIndex",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuditLogsResponse := _AuditLogsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuditLogsResponse)

	if err != nil {
		return err
	}

	*o = AuditLogsResponse(varAuditLogsResponse)

	return err
}

type NullableAuditLogsResponse struct {
	value *AuditLogsResponse
	isSet bool
}

func (v NullableAuditLogsResponse) Get() *AuditLogsResponse {
	return v.value
}

func (v *NullableAuditLogsResponse) Set(val *AuditLogsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuditLogsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuditLogsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuditLogsResponse(val *AuditLogsResponse) *NullableAuditLogsResponse {
	return &NullableAuditLogsResponse{value: val, isSet: true}
}

func (v NullableAuditLogsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuditLogsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


