/*
Vault Hub Server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateAPIKeyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAPIKeyResponse{}

// CreateAPIKeyResponse struct for CreateAPIKeyResponse
type CreateAPIKeyResponse struct {
	ApiKey VaultAPIKey `json:"apiKey"`
	// The generated API key (only shown once)
	Key string `json:"key"`
}

type _CreateAPIKeyResponse CreateAPIKeyResponse

// NewCreateAPIKeyResponse instantiates a new CreateAPIKeyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAPIKeyResponse(apiKey VaultAPIKey, key string) *CreateAPIKeyResponse {
	this := CreateAPIKeyResponse{}
	this.ApiKey = apiKey
	this.Key = key
	return &this
}

// NewCreateAPIKeyResponseWithDefaults instantiates a new CreateAPIKeyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAPIKeyResponseWithDefaults() *CreateAPIKeyResponse {
	this := CreateAPIKeyResponse{}
	return &this
}

// GetApiKey returns the ApiKey field value
func (o *CreateAPIKeyResponse) GetApiKey() VaultAPIKey {
	if o == nil {
		var ret VaultAPIKey
		return ret
	}

	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
func (o *CreateAPIKeyResponse) GetApiKeyOk() (*VaultAPIKey, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKey, true
}

// SetApiKey sets field value
func (o *CreateAPIKeyResponse) SetApiKey(v VaultAPIKey) {
	o.ApiKey = v
}

// GetKey returns the Key field value
func (o *CreateAPIKeyResponse) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *CreateAPIKeyResponse) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *CreateAPIKeyResponse) SetKey(v string) {
	o.Key = v
}

func (o CreateAPIKeyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAPIKeyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["apiKey"] = o.ApiKey
	toSerialize["key"] = o.Key
	return toSerialize, nil
}

func (o *CreateAPIKeyResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"apiKey",
		"key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAPIKeyResponse := _CreateAPIKeyResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAPIKeyResponse)

	if err != nil {
		return err
	}

	*o = CreateAPIKeyResponse(varCreateAPIKeyResponse)

	return err
}

type NullableCreateAPIKeyResponse struct {
	value *CreateAPIKeyResponse
	isSet bool
}

func (v NullableCreateAPIKeyResponse) Get() *CreateAPIKeyResponse {
	return v.value
}

func (v *NullableCreateAPIKeyResponse) Set(val *CreateAPIKeyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAPIKeyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAPIKeyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAPIKeyResponse(val *CreateAPIKeyResponse) *NullableCreateAPIKeyResponse {
	return &NullableCreateAPIKeyResponse{value: val, isSet: true}
}

func (v NullableCreateAPIKeyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAPIKeyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


