/*
Vault Hub Server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VaultFilterOptionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VaultFilterOptionsResponse{}

// VaultFilterOptionsResponse struct for VaultFilterOptionsResponse
type VaultFilterOptionsResponse struct {
	// List of vaults for filter dropdowns
	Vaults []VaultFilterOption `json:"vaults"`
}

type _VaultFilterOptionsResponse VaultFilterOptionsResponse

// NewVaultFilterOptionsResponse instantiates a new VaultFilterOptionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVaultFilterOptionsResponse(vaults []VaultFilterOption) *VaultFilterOptionsResponse {
	this := VaultFilterOptionsResponse{}
	this.Vaults = vaults
	return &this
}

// NewVaultFilterOptionsResponseWithDefaults instantiates a new VaultFilterOptionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVaultFilterOptionsResponseWithDefaults() *VaultFilterOptionsResponse {
	this := VaultFilterOptionsResponse{}
	return &this
}

// GetVaults returns the Vaults field value
func (o *VaultFilterOptionsResponse) GetVaults() []VaultFilterOption {
	if o == nil {
		var ret []VaultFilterOption
		return ret
	}

	return o.Vaults
}

// GetVaultsOk returns a tuple with the Vaults field value
// and a boolean to check if the value has been set.
func (o *VaultFilterOptionsResponse) GetVaultsOk() ([]VaultFilterOption, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vaults, true
}

// SetVaults sets field value
func (o *VaultFilterOptionsResponse) SetVaults(v []VaultFilterOption) {
	o.Vaults = v
}

func (o VaultFilterOptionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VaultFilterOptionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["vaults"] = o.Vaults
	return toSerialize, nil
}

func (o *VaultFilterOptionsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"vaults",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVaultFilterOptionsResponse := _VaultFilterOptionsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVaultFilterOptionsResponse)

	if err != nil {
		return err
	}

	*o = VaultFilterOptionsResponse(varVaultFilterOptionsResponse)

	return err
}

type NullableVaultFilterOptionsResponse struct {
	value *VaultFilterOptionsResponse
	isSet bool
}

func (v NullableVaultFilterOptionsResponse) Get() *VaultFilterOptionsResponse {
	return v.value
}

func (v *NullableVaultFilterOptionsResponse) Set(val *VaultFilterOptionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVaultFilterOptionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVaultFilterOptionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVaultFilterOptionsResponse(val *VaultFilterOptionsResponse) *NullableVaultFilterOptionsResponse {
	return &NullableVaultFilterOptionsResponse{value: val, isSet: true}
}

func (v NullableVaultFilterOptionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVaultFilterOptionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


