/*
Vault Hub Server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PasswordResetConfirmRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PasswordResetConfirmRequest{}

// PasswordResetConfirmRequest struct for PasswordResetConfirmRequest
type PasswordResetConfirmRequest struct {
	Token string `json:"token"`
	NewPassword string `json:"newPassword"`
}

type _PasswordResetConfirmRequest PasswordResetConfirmRequest

// NewPasswordResetConfirmRequest instantiates a new PasswordResetConfirmRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPasswordResetConfirmRequest(token string, newPassword string) *PasswordResetConfirmRequest {
	this := PasswordResetConfirmRequest{}
	this.Token = token
	this.NewPassword = newPassword
	return &this
}

// NewPasswordResetConfirmRequestWithDefaults instantiates a new PasswordResetConfirmRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPasswordResetConfirmRequestWithDefaults() *PasswordResetConfirmRequest {
	this := PasswordResetConfirmRequest{}
	return &this
}

// GetToken returns the Token field value
func (o *PasswordResetConfirmRequest) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *PasswordResetConfirmRequest) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *PasswordResetConfirmRequest) SetToken(v string) {
	o.Token = v
}

// GetNewPassword returns the NewPassword field value
func (o *PasswordResetConfirmRequest) GetNewPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NewPassword
}

// GetNewPasswordOk returns a tuple with the NewPassword field value
// and a boolean to check if the value has been set.
func (o *PasswordResetConfirmRequest) GetNewPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewPassword, true
}

// SetNewPassword sets field value
func (o *PasswordResetConfirmRequest) SetNewPassword(v string) {
	o.NewPassword = v
}

func (o PasswordResetConfirmRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PasswordResetConfirmRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	toSerialize["newPassword"] = o.NewPassword
	return toSerialize, nil
}

func (o *PasswordResetConfirmRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
		"newPassword",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPasswordResetConfirmRequest := _PasswordResetConfirmRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPasswordResetConfirmRequest)

	if err != nil {
		return err
	}

	*o = PasswordResetConfirmRequest(varPasswordResetConfirmRequest)

	return err
}

type NullablePasswordResetConfirmRequest struct {
	value *PasswordResetConfirmRequest
	isSet bool
}

func (v NullablePasswordResetConfirmRequest) Get() *PasswordResetConfirmRequest {
	return v.value
}

func (v *NullablePasswordResetConfirmRequest) Set(val *PasswordResetConfirmRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePasswordResetConfirmRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePasswordResetConfirmRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePasswordResetConfirmRequest(val *PasswordResetConfirmRequest) *NullablePasswordResetConfirmRequest {
	return &NullablePasswordResetConfirmRequest{value: val, isSet: true}
}

func (v NullablePasswordResetConfirmRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePasswordResetConfirmRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


