/*
Vault Hub Server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VaultFilterOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VaultFilterOption{}

// VaultFilterOption struct for VaultFilterOption
type VaultFilterOption struct {
	// Unique identifier for the vault
	UniqueId string `json:"uniqueId"`
	// Human-readable name
	Name string `json:"name"`
}

type _VaultFilterOption VaultFilterOption

// NewVaultFilterOption instantiates a new VaultFilterOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVaultFilterOption(uniqueId string, name string) *VaultFilterOption {
	this := VaultFilterOption{}
	this.UniqueId = uniqueId
	this.Name = name
	return &this
}

// NewVaultFilterOptionWithDefaults instantiates a new VaultFilterOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVaultFilterOptionWithDefaults() *VaultFilterOption {
	this := VaultFilterOption{}
	return &this
}

// GetUniqueId returns the UniqueId field value
func (o *VaultFilterOption) GetUniqueId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UniqueId
}

// GetUniqueIdOk returns a tuple with the UniqueId field value
// and a boolean to check if the value has been set.
func (o *VaultFilterOption) GetUniqueIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UniqueId, true
}

// SetUniqueId sets field value
func (o *VaultFilterOption) SetUniqueId(v string) {
	o.UniqueId = v
}

// GetName returns the Name field value
func (o *VaultFilterOption) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VaultFilterOption) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VaultFilterOption) SetName(v string) {
	o.Name = v
}

func (o VaultFilterOption) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VaultFilterOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uniqueId"] = o.UniqueId
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *VaultFilterOption) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uniqueId",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVaultFilterOption := _VaultFilterOption{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVaultFilterOption)

	if err != nil {
		return err
	}

	*o = VaultFilterOption(varVaultFilterOption)

	return err
}

type NullableVaultFilterOption struct {
	value *VaultFilterOption
	isSet bool
}

func (v NullableVaultFilterOption) Get() *VaultFilterOption {
	return v.value
}

func (v *NullableVaultFilterOption) Set(val *VaultFilterOption) {
	v.value = val
	v.isSet = true
}

func (v NullableVaultFilterOption) IsSet() bool {
	return v.isSet
}

func (v *NullableVaultFilterOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVaultFilterOption(val *VaultFilterOption) *NullableVaultFilterOption {
	return &NullableVaultFilterOption{value: val, isSet: true}
}

func (v NullableVaultFilterOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVaultFilterOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


