/*
Vault Hub Server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VaultsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VaultsResponse{}

// VaultsResponse struct for VaultsResponse
type VaultsResponse struct {
	// Page of vault records for the authenticated user
	Vaults []VaultLite `json:"vaults"`
	// Total number of vaults available for pagination
	TotalCount int32 `json:"totalCount"`
	// Number of vaults returned per page
	PageSize int32 `json:"pageSize"`
	// Current page index (starting from 1)
	PageIndex int32 `json:"pageIndex"`
}

type _VaultsResponse VaultsResponse

// NewVaultsResponse instantiates a new VaultsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVaultsResponse(vaults []VaultLite, totalCount int32, pageSize int32, pageIndex int32) *VaultsResponse {
	this := VaultsResponse{}
	this.Vaults = vaults
	this.TotalCount = totalCount
	this.PageSize = pageSize
	this.PageIndex = pageIndex
	return &this
}

// NewVaultsResponseWithDefaults instantiates a new VaultsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVaultsResponseWithDefaults() *VaultsResponse {
	this := VaultsResponse{}
	return &this
}

// GetVaults returns the Vaults field value
func (o *VaultsResponse) GetVaults() []VaultLite {
	if o == nil {
		var ret []VaultLite
		return ret
	}

	return o.Vaults
}

// GetVaultsOk returns a tuple with the Vaults field value
// and a boolean to check if the value has been set.
func (o *VaultsResponse) GetVaultsOk() ([]VaultLite, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vaults, true
}

// SetVaults sets field value
func (o *VaultsResponse) SetVaults(v []VaultLite) {
	o.Vaults = v
}

// GetTotalCount returns the TotalCount field value
func (o *VaultsResponse) GetTotalCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *VaultsResponse) GetTotalCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *VaultsResponse) SetTotalCount(v int32) {
	o.TotalCount = v
}

// GetPageSize returns the PageSize field value
func (o *VaultsResponse) GetPageSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *VaultsResponse) GetPageSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *VaultsResponse) SetPageSize(v int32) {
	o.PageSize = v
}

// GetPageIndex returns the PageIndex field value
func (o *VaultsResponse) GetPageIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageIndex
}

// GetPageIndexOk returns a tuple with the PageIndex field value
// and a boolean to check if the value has been set.
func (o *VaultsResponse) GetPageIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageIndex, true
}

// SetPageIndex sets field value
func (o *VaultsResponse) SetPageIndex(v int32) {
	o.PageIndex = v
}

func (o VaultsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VaultsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["vaults"] = o.Vaults
	toSerialize["totalCount"] = o.TotalCount
	toSerialize["pageSize"] = o.PageSize
	toSerialize["pageIndex"] = o.PageIndex
	return toSerialize, nil
}

func (o *VaultsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"vaults",
		"totalCount",
		"pageSize",
		"pageIndex",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVaultsResponse := _VaultsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVaultsResponse)

	if err != nil {
		return err
	}

	*o = VaultsResponse(varVaultsResponse)

	return err
}

type NullableVaultsResponse struct {
	value *VaultsResponse
	isSet bool
}

func (v NullableVaultsResponse) Get() *VaultsResponse {
	return v.value
}

func (v *NullableVaultsResponse) Set(val *VaultsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVaultsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVaultsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVaultsResponse(val *VaultsResponse) *NullableVaultsResponse {
	return &NullableVaultsResponse{value: val, isSet: true}
}

func (v NullableVaultsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVaultsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


