/*
Vault Hub Server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SignupResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignupResponse{}

// SignupResponse struct for SignupResponse
type SignupResponse struct {
	Token string `json:"token"`
}

type _SignupResponse SignupResponse

// NewSignupResponse instantiates a new SignupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignupResponse(token string) *SignupResponse {
	this := SignupResponse{}
	this.Token = token
	return &this
}

// NewSignupResponseWithDefaults instantiates a new SignupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignupResponseWithDefaults() *SignupResponse {
	this := SignupResponse{}
	return &this
}

// GetToken returns the Token field value
func (o *SignupResponse) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *SignupResponse) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *SignupResponse) SetToken(v string) {
	o.Token = v
}

func (o SignupResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignupResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

func (o *SignupResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSignupResponse := _SignupResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSignupResponse)

	if err != nil {
		return err
	}

	*o = SignupResponse(varSignupResponse)

	return err
}

type NullableSignupResponse struct {
	value *SignupResponse
	isSet bool
}

func (v NullableSignupResponse) Get() *SignupResponse {
	return v.value
}

func (v *NullableSignupResponse) Set(val *SignupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSignupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSignupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignupResponse(val *SignupResponse) *NullableSignupResponse {
	return &NullableSignupResponse{value: val, isSet: true}
}

func (v NullableSignupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


