/*
Vault Hub Server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SignupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignupRequest{}

// SignupRequest struct for SignupRequest
type SignupRequest struct {
	Email string `json:"email"`
	Password string `json:"password"`
	Name string `json:"name"`
}

type _SignupRequest SignupRequest

// NewSignupRequest instantiates a new SignupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignupRequest(email string, password string, name string) *SignupRequest {
	this := SignupRequest{}
	this.Email = email
	this.Password = password
	this.Name = name
	return &this
}

// NewSignupRequestWithDefaults instantiates a new SignupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignupRequestWithDefaults() *SignupRequest {
	this := SignupRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *SignupRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *SignupRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *SignupRequest) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *SignupRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *SignupRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *SignupRequest) SetPassword(v string) {
	o.Password = v
}

// GetName returns the Name field value
func (o *SignupRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SignupRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SignupRequest) SetName(v string) {
	o.Name = v
}

func (o SignupRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["password"] = o.Password
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *SignupRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"password",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSignupRequest := _SignupRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSignupRequest)

	if err != nil {
		return err
	}

	*o = SignupRequest(varSignupRequest)

	return err
}

type NullableSignupRequest struct {
	value *SignupRequest
	isSet bool
}

func (v NullableSignupRequest) Get() *SignupRequest {
	return v.value
}

func (v *NullableSignupRequest) Set(val *SignupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSignupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSignupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignupRequest(val *SignupRequest) *NullableSignupRequest {
	return &NullableSignupRequest{value: val, isSet: true}
}

func (v NullableSignupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


