/*
Vault Hub Server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuditMetricsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuditMetricsResponse{}

// AuditMetricsResponse struct for AuditMetricsResponse
type AuditMetricsResponse struct {
	// Total number of audit events in the last 30 days
	TotalEventsLast30Days int32 `json:"totalEventsLast30Days"`
	// Number of audit events in the last 24 hours
	EventsCountLast24Hours int32 `json:"eventsCountLast24Hours"`
	// Number of vault-related events in the last 30 days
	VaultEventsLast30Days int32 `json:"vaultEventsLast30Days"`
	// Number of API key-related events in the last 30 days
	ApiKeyEventsLast30Days int32 `json:"apiKeyEventsLast30Days"`
}

type _AuditMetricsResponse AuditMetricsResponse

// NewAuditMetricsResponse instantiates a new AuditMetricsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuditMetricsResponse(totalEventsLast30Days int32, eventsCountLast24Hours int32, vaultEventsLast30Days int32, apiKeyEventsLast30Days int32) *AuditMetricsResponse {
	this := AuditMetricsResponse{}
	this.TotalEventsLast30Days = totalEventsLast30Days
	this.EventsCountLast24Hours = eventsCountLast24Hours
	this.VaultEventsLast30Days = vaultEventsLast30Days
	this.ApiKeyEventsLast30Days = apiKeyEventsLast30Days
	return &this
}

// NewAuditMetricsResponseWithDefaults instantiates a new AuditMetricsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuditMetricsResponseWithDefaults() *AuditMetricsResponse {
	this := AuditMetricsResponse{}
	return &this
}

// GetTotalEventsLast30Days returns the TotalEventsLast30Days field value
func (o *AuditMetricsResponse) GetTotalEventsLast30Days() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalEventsLast30Days
}

// GetTotalEventsLast30DaysOk returns a tuple with the TotalEventsLast30Days field value
// and a boolean to check if the value has been set.
func (o *AuditMetricsResponse) GetTotalEventsLast30DaysOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalEventsLast30Days, true
}

// SetTotalEventsLast30Days sets field value
func (o *AuditMetricsResponse) SetTotalEventsLast30Days(v int32) {
	o.TotalEventsLast30Days = v
}

// GetEventsCountLast24Hours returns the EventsCountLast24Hours field value
func (o *AuditMetricsResponse) GetEventsCountLast24Hours() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EventsCountLast24Hours
}

// GetEventsCountLast24HoursOk returns a tuple with the EventsCountLast24Hours field value
// and a boolean to check if the value has been set.
func (o *AuditMetricsResponse) GetEventsCountLast24HoursOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventsCountLast24Hours, true
}

// SetEventsCountLast24Hours sets field value
func (o *AuditMetricsResponse) SetEventsCountLast24Hours(v int32) {
	o.EventsCountLast24Hours = v
}

// GetVaultEventsLast30Days returns the VaultEventsLast30Days field value
func (o *AuditMetricsResponse) GetVaultEventsLast30Days() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.VaultEventsLast30Days
}

// GetVaultEventsLast30DaysOk returns a tuple with the VaultEventsLast30Days field value
// and a boolean to check if the value has been set.
func (o *AuditMetricsResponse) GetVaultEventsLast30DaysOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VaultEventsLast30Days, true
}

// SetVaultEventsLast30Days sets field value
func (o *AuditMetricsResponse) SetVaultEventsLast30Days(v int32) {
	o.VaultEventsLast30Days = v
}

// GetApiKeyEventsLast30Days returns the ApiKeyEventsLast30Days field value
func (o *AuditMetricsResponse) GetApiKeyEventsLast30Days() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ApiKeyEventsLast30Days
}

// GetApiKeyEventsLast30DaysOk returns a tuple with the ApiKeyEventsLast30Days field value
// and a boolean to check if the value has been set.
func (o *AuditMetricsResponse) GetApiKeyEventsLast30DaysOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKeyEventsLast30Days, true
}

// SetApiKeyEventsLast30Days sets field value
func (o *AuditMetricsResponse) SetApiKeyEventsLast30Days(v int32) {
	o.ApiKeyEventsLast30Days = v
}

func (o AuditMetricsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuditMetricsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["totalEventsLast30Days"] = o.TotalEventsLast30Days
	toSerialize["eventsCountLast24Hours"] = o.EventsCountLast24Hours
	toSerialize["vaultEventsLast30Days"] = o.VaultEventsLast30Days
	toSerialize["apiKeyEventsLast30Days"] = o.ApiKeyEventsLast30Days
	return toSerialize, nil
}

func (o *AuditMetricsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"totalEventsLast30Days",
		"eventsCountLast24Hours",
		"vaultEventsLast30Days",
		"apiKeyEventsLast30Days",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuditMetricsResponse := _AuditMetricsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuditMetricsResponse)

	if err != nil {
		return err
	}

	*o = AuditMetricsResponse(varAuditMetricsResponse)

	return err
}

type NullableAuditMetricsResponse struct {
	value *AuditMetricsResponse
	isSet bool
}

func (v NullableAuditMetricsResponse) Get() *AuditMetricsResponse {
	return v.value
}

func (v *NullableAuditMetricsResponse) Set(val *AuditMetricsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuditMetricsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuditMetricsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuditMetricsResponse(val *AuditMetricsResponse) *NullableAuditMetricsResponse {
	return &NullableAuditMetricsResponse{value: val, isSet: true}
}

func (v NullableAuditMetricsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuditMetricsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


