/*
Vault Hub Server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the APIKeysResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &APIKeysResponse{}

// APIKeysResponse struct for APIKeysResponse
type APIKeysResponse struct {
	ApiKeys []VaultAPIKey `json:"apiKeys"`
	// Total number of API keys
	TotalCount int32 `json:"totalCount"`
	// Number of API keys per page
	PageSize int32 `json:"pageSize"`
	// Current page index (starting from 1)
	PageIndex int32 `json:"pageIndex"`
}

type _APIKeysResponse APIKeysResponse

// NewAPIKeysResponse instantiates a new APIKeysResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPIKeysResponse(apiKeys []VaultAPIKey, totalCount int32, pageSize int32, pageIndex int32) *APIKeysResponse {
	this := APIKeysResponse{}
	this.ApiKeys = apiKeys
	this.TotalCount = totalCount
	this.PageSize = pageSize
	this.PageIndex = pageIndex
	return &this
}

// NewAPIKeysResponseWithDefaults instantiates a new APIKeysResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIKeysResponseWithDefaults() *APIKeysResponse {
	this := APIKeysResponse{}
	return &this
}

// GetApiKeys returns the ApiKeys field value
func (o *APIKeysResponse) GetApiKeys() []VaultAPIKey {
	if o == nil {
		var ret []VaultAPIKey
		return ret
	}

	return o.ApiKeys
}

// GetApiKeysOk returns a tuple with the ApiKeys field value
// and a boolean to check if the value has been set.
func (o *APIKeysResponse) GetApiKeysOk() ([]VaultAPIKey, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApiKeys, true
}

// SetApiKeys sets field value
func (o *APIKeysResponse) SetApiKeys(v []VaultAPIKey) {
	o.ApiKeys = v
}

// GetTotalCount returns the TotalCount field value
func (o *APIKeysResponse) GetTotalCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *APIKeysResponse) GetTotalCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *APIKeysResponse) SetTotalCount(v int32) {
	o.TotalCount = v
}

// GetPageSize returns the PageSize field value
func (o *APIKeysResponse) GetPageSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *APIKeysResponse) GetPageSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *APIKeysResponse) SetPageSize(v int32) {
	o.PageSize = v
}

// GetPageIndex returns the PageIndex field value
func (o *APIKeysResponse) GetPageIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageIndex
}

// GetPageIndexOk returns a tuple with the PageIndex field value
// and a boolean to check if the value has been set.
func (o *APIKeysResponse) GetPageIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageIndex, true
}

// SetPageIndex sets field value
func (o *APIKeysResponse) SetPageIndex(v int32) {
	o.PageIndex = v
}

func (o APIKeysResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o APIKeysResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["apiKeys"] = o.ApiKeys
	toSerialize["totalCount"] = o.TotalCount
	toSerialize["pageSize"] = o.PageSize
	toSerialize["pageIndex"] = o.PageIndex
	return toSerialize, nil
}

func (o *APIKeysResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"apiKeys",
		"totalCount",
		"pageSize",
		"pageIndex",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAPIKeysResponse := _APIKeysResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAPIKeysResponse)

	if err != nil {
		return err
	}

	*o = APIKeysResponse(varAPIKeysResponse)

	return err
}

type NullableAPIKeysResponse struct {
	value *APIKeysResponse
	isSet bool
}

func (v NullableAPIKeysResponse) Get() *APIKeysResponse {
	return v.value
}

func (v *NullableAPIKeysResponse) Set(val *APIKeysResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAPIKeysResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAPIKeysResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPIKeysResponse(val *APIKeysResponse) *NullableAPIKeysResponse {
	return &NullableAPIKeysResponse{value: val, isSet: true}
}

func (v NullableAPIKeysResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPIKeysResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


